#!/usr/bin/env python3
"""emit_harness.py — quick single-contract Echidna/Medusa harness (Section A6).

Truent's own fuzzer (`truent fuzz --dynamic`) needs no harness and no external
toolchain — it auto-detects invariants and shrinks a violation to a minimal
PoC in one binary. This generator exists for interop: teams standardised on
Echidna or Medusa get a ready property contract for the SAME invariant shapes
Truent checks, so Truent is a strict superset of a harness generator, not a
replacement that locks you in. For a full protocol suite (handlers, ghosts,
snapshots, discovery agents) use Section B of SKILL.md instead; both write the
same `test/fizz/` + `fizz_data/` layout and can coexist.

Writes:
  <suite-dir>/TruentHarness.sol      Echidna/Medusa property contract
  <project-root>/medusa.json         runnable Medusa config (unless present)
  <project-root>/echidna.yaml        runnable Echidna config (unless present)
  <meta-dir>/properties.invar        note: these shapes are auto-detected by
                                     the native fuzzer, so the file only
                                     documents that; add protocol-specific
                                     properties to it by hand (references/dsl.md)

Usage:
  emit_harness.py --contract Vault --path src/Vault.sol \
      --props conservation,supply-monotonic,owner-stable --actors 3 \
      --suite-dir test/fizz --meta-dir fizz_data [--project-root .] [--force]
"""
import argparse
import json
import os
import sys

PROP_LIBRARY = {
    # name -> (property function, description, body lines)
    "conservation": (
        "property_conservation",
        "sum(balanceOf(actor)) over the actor set equals totalSupply()",
        [
            "uint256 sum;",
            "for (uint256 i = 0; i < actors.length; i++) {",
            "    sum += target.balanceOf(actors[i]);",
            "}",
            "return sum == target.totalSupply();",
        ],
    ),
    "supply-monotonic": (
        "property_supply_monotonic",
        "totalSupply() never decreases across the campaign",
        [
            "uint256 s = target.totalSupply();",
            "if (s < _lastSupply) return false;",
            "_lastSupply = s;",
            "return true;",
        ],
    ),
    "owner-stable": (
        "property_owner_unchanged_by_others",
        "owner() only changes via the owner (no unprivileged takeover)",
        [
            "return target.owner() == _expectedOwner;",
        ],
    ),
}


def gen_solidity(contract, rel_path, props, actors):
    lines = [
        "// SPDX-License-Identifier: MIT",
        "pragma solidity ^0.8.0;",
        "",
        f'import {{{contract}}} from "{rel_path}";',
        "",
        "/// @notice Echidna/Medusa property harness generated by truent-fuzz (Section A6).",
        "/// Assertions mirror the invariant shapes Truent's native fuzzer",
        "/// (`truent fuzz --dynamic`) checks automatically. Wire the",
        "/// constructor deployment to your real setup where marked TODO.",
        "/// Results from Echidna/Medusa are EXTERNAL evidence; the native run is VERIFIED-PROVEN.",
        "contract TruentHarness {",
        f"    {contract} internal target;",
        f"    address[{actors}] internal actors;",
        "    uint256 internal _lastSupply;",
        "    address internal _expectedOwner;",
        "",
        "    constructor() {",
        "        // TODO: deploy `target` the way your project does, and",
        "        // seed the actor set. Echidna/Medusa will call target's",
        "        // external functions from these senders.",
        f"        target = new {contract}();",
    ]
    for i in range(actors):
        lines.append(f"        actors[{i}] = address(uint160(0x10000 * ({i} + 1)));")
    lines += [
        "        _lastSupply = target.totalSupply();",
        "        _expectedOwner = address(this);",
        "    }",
        "",
    ]
    for key in props:
        entry = PROP_LIBRARY.get(key)
        if not entry:
            lines.append(f"    // (unknown property '{key}' skipped)")
            continue
        fn, desc, body = entry
        mutability = "view " if key != "supply-monotonic" else ""
        lines.append(f"    /// @notice {desc}")
        lines.append(f"    function {fn}() public {mutability}returns (bool) {{")
        lines += [f"        {b}" for b in body]
        lines.append("    }")
        lines.append("")
    lines.append("}")
    return "\n".join(lines) + "\n"


def gen_medusa(meta_dir, suite_dir):
    return json.dumps({
        "fuzzing": {
            "workers": 8,
            "testLimit": 100000,
            "callSequenceLength": 100,
            "corpusDirectory": f"{meta_dir}/corpus_medusa",
            "coverageEnabled": True,
            "deploymentOrder": ["TruentHarness"],
            "targetContracts": ["TruentHarness"],
            "senderAddresses": ["0x10000", "0x20000", "0x30000"],
            "testing": {
                "propertyTesting": {"enabled": True, "testPrefixes": ["property_"]},
                "assertionTesting": {"enabled": True},
            },
        },
        "compilation": {
            "platform": "crytic-compile",
            "platformConfig": {"target": ".", "args": ["--foundry-compile-all"]},
        },
        "logging": {"logDirectory": f"{meta_dir}/logs_medusa"},
    }, indent=2) + "\n"


def gen_echidna(meta_dir, suite_dir):
    return (
        'testMode: "property"\n'
        'prefix: "property_"\n'
        "testLimit: 100000\n"
        "seqLen: 100\n"
        "coverage: true\n"
        f'corpusDir: "{meta_dir}/corpus_echidna"\n'
        'cryticArgs: ["--foundry-compile-all"]\n'
        f"# run: echidna . --contract TruentHarness --config echidna.yaml\n"
    )


def gen_invar(contract, props):
    lines = [
        f"// properties.invar for {contract} — written by emit_harness.py (truent-fuzz Section A6)",
        "// The shapes emitted into TruentHarness.sol (" + ", ".join(props) + ")",
        "// are AUTO-DETECTED by `truent fuzz --dynamic --chain evm` from the ABI",
        "// (totalSupply/balanceOf conservation, monotonic accumulator getters,",
        "// owner()/transferOwnership access control) — they need no DSL.",
        "// Add protocol-specific state predicates here, one per block, e.g.:",
        "//   invariant UnderCap { total_supply <= max_supply }",
        "// Every identifier must bind to a zero-argument view on the contract",
        "// (see references/dsl.md); an unbound identifier is an error, not a skip.",
        "",
    ]
    return "\n".join(lines) + "\n"


def write_unless_exists(path, content, force):
    if os.path.exists(path) and not force:
        print(f"  [exists] {path} (pass --force to overwrite)")
        return False
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)
    print(f"  [new]    {path}")
    return True


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--contract", required=True)
    ap.add_argument("--path", required=True, help="path to the target contract source (relative to project root)")
    ap.add_argument("--props", default="conservation,supply-monotonic",
                    help="comma list of: " + ", ".join(PROP_LIBRARY))
    ap.add_argument("--actors", type=int, default=3)
    ap.add_argument("--project-root", default=".")
    ap.add_argument("--suite-dir", default="test/fizz", help="suite directory relative to project root (default test/fizz)")
    ap.add_argument("--meta-dir", default="fizz_data", help="metadata directory relative to project root (default fizz_data)")
    ap.add_argument("--out", help="deprecated alias for --suite-dir")
    ap.add_argument("--force", action="store_true", help="overwrite existing files")
    a = ap.parse_args()

    suite_rel = a.out or a.suite_dir
    root = os.path.abspath(a.project_root)
    suite_dir = os.path.join(root, suite_rel)
    meta_dir = os.path.join(root, a.meta_dir)
    props = [p.strip() for p in a.props.split(",") if p.strip()]
    unknown = [p for p in props if p not in PROP_LIBRARY]
    if unknown:
        print(f"warning: unknown props skipped: {', '.join(unknown)}", file=sys.stderr)

    # import path from the suite dir back to the contract source
    rel_path = os.path.relpath(os.path.join(root, a.path), suite_dir).replace(os.sep, "/")
    if not rel_path.startswith("."):
        rel_path = "./" + rel_path

    print(f"Writing quick harness into {suite_rel}/ (configs at project root):")
    write_unless_exists(os.path.join(suite_dir, "TruentHarness.sol"), gen_solidity(a.contract, rel_path, props, a.actors), a.force)
    write_unless_exists(os.path.join(root, "medusa.json"), gen_medusa(a.meta_dir, suite_rel), a.force)
    write_unless_exists(os.path.join(root, "echidna.yaml"), gen_echidna(a.meta_dir, suite_rel), a.force)
    write_unless_exists(os.path.join(meta_dir, "properties.invar"), gen_invar(a.contract, props), a.force)

    print("\nRun natively (recommended, no toolchain; VERIFIED-PROVEN on violation):")
    print(f"  truent fuzz {a.path} --dynamic --chain evm --iterations 1000 --seed 1")
    print(f"  truent fuzz {a.path} --dynamic --chain evm --invariants {a.meta_dir}/properties.invar   # once you add DSL properties")
    print("Or with the emitted harness (EXTERNAL):")
    print("  medusa fuzz --config medusa.json")
    print("  echidna . --contract TruentHarness --config echidna.yaml")


if __name__ == "__main__":
    main()
